# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7efe41df1843a79924a7cb5558d42154198c937cf7b1de139716cfc7c076d87406fe4a1a573dbf0aef2bb82d82ae037d158f9149898b2723efec8476f210b881

test:
  secret_key_base: 91e8ecd52cfcce84db1217298653f40e8fcf15193d297b8e20e92ef2b59ab2c8973d342fe82409ddd5b7e0e7e8b67113872f79cbad764217d5987365fe05558f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
